# Review Data Set

In [1]:
import networkx as nx
dolphins_grap = nx.read_gml("..\data\dolphins.gml")
print nx.info(dolphins_grap)
print nx.info(dolphins_grap, n=1)

Name: 
Type: Graph
Number of nodes: 62
Number of edges: 159
Average degree:   5.1290
Node 1 has the following properties:
Degree: 8
Neighbors: 36 41 17 19 54 26 27 28


In [19]:
dolphins_grap.node[0]['label']

u'Beak'

In [3]:
d_matr = nx.to_numpy_matrix(dolphins_grap, nodelist=range(62))

In [4]:
print d_matr

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  1.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  1. ...,  0.  0.  0.]]


# Input

In [5]:
import numpy as np
G = d_matr + np.eye(d_matr.shape[1])

# Test Euclidean distance


In [6]:
from scipy.spatial import distance
a = [1,2,3]
b = [4,5,6]
dst = distance.euclidean(a,b)
print dst

5.19615242271


In [8]:
size=62
S = np.eye(size)
for i in range(size):
    for j in range(size):
        similar = distance.euclidean(G[i],G[j])
        S[i][j] = similar
print S[1]

[ 4.          0.          3.74165739  3.60555128  3.31662479  3.74165739
  3.46410162  3.          3.74165739  3.60555128  3.87298335  3.31662479
  3.31662479  3.46410162  4.69041576  4.12310563  4.          3.60555128
  4.12310563  2.82842712  3.87298335  4.          3.          3.31662479
  4.          2.64575131  2.64575131  2.64575131  3.31662479  4.35889894
  3.31662479  3.          3.60555128  4.47213595  3.87298335  3.31662479
  3.60555128  4.35889894  4.24264069  3.16227766  4.          3.          4.
  4.12310563  3.74165739  4.58257569  3.46410162  3.74165739  3.31662479
  3.46410162  4.12310563  4.47213595  3.74165739  3.46410162  3.
  3.46410162  3.46410162  3.60555128  3.31662479  3.60555128  3.31662479
  3.60555128]


# KNN Algorithm

In [ ]:
def predict_knn(G,S,k):
    size = S.shape[1]
    P = np.zeros((size,size))
    for i in range(size):
        for j in range(size):
            if i!= j and G.item(i,j) != 1.0:
                #find top k similar of d_j and compute predict 
                d_j =  S[:][j]
                index = d_j.argsort()[-k:][::-1]
                top_d_j = d_j[d_j.argsort()[-k:][::-1]]
                print top_d_j
                print index
                Connect = G[:][j].T
                print Connect
                P[i][j] = top_d_j*Connect[index]/sum(top_d_j)
            else:
                P[i][j] = -1
            
    return P

Predict = predict_knn(G,S,3)
print Predict

[ 4.69041576  4.58257569  4.47213595]
[14 45 33]
[[ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[ 4.24264069  4.12310563  4.        ]
[14 45 51]
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
[ 3.87298335  3.74165739  3.7416